### ISSUE TITLE
celery_enable_all clarification

### ISSUE THREAD

**Issue by hassa** [jmoiron/johnny-cache#12]
I see the johnny.utils.celery_enable_all function, but it is not clear where it should be called from.

I see this same question posted on the (old?) bitbucket repo too in issue 47 but it was never answered.

Any clarification would be much appreciated.

**Comment by chrismarceloph** [comment]
I tried to apply to celery_enable_all the steps in the docs for [enabling johnny beyond the middleware](https://johnny-cache.readthedocs.org/en/latest/queryset_cache.html#using-with-scripts-management-commands-asynchronous-workers-and-the-shell), and it worked.

So add this to your project's `__init__.py`:

``` python
from johnny.cache import celery_enable_all
celery_enable_all()
```

**Comment by hassa** [comment]
I must have missed the __init__.py bit in the docs, thanks!
