### ISSUE TITLE
settings.py should not be in repo

### ISSUE THREAD

**Issue by adriannye** [jmoiron/johnny-cache#20]
In trunk (commit 0f16eb185db32c33bda8f6d7e5e58a6a73c11fe4)
there is a settings.py file.  I imagine it's here due to a accidental commit.

If it is intentional, then it can't import "proj.urls" which is unlikely to exist for anyone else.

**Comment by jself** [comment]
The file is actually used for testing and is only really used for setting up the database and cache backend. It's not installed with johnny cache, but is intended to be there. It's likely that the file will be extended to support multiple databases, etc, but the urls doesn't actually matter. I'll try to remove it and if the tests fail will put it back.
