### ISSUE TITLE
MemcachedError in Admin

### ISSUE THREAD

**Issue by typeshige** [jmoiron/johnny-cache#3]
Hi,

Using Django 1.4 and in admin I have a model that I can't see the detail view.

```
MemcachedError at /admin/nims/article/1141/
error 37 from memcached_set: SYSTEM ERROR(Resource temporarily unavailable), host: 127.0.0.1:11211 -> libmemcached/io.cc:358
Request Method: GET
Request URL:    http://127.0.0.1:8007/admin/nims/article/1141/
Django Version: 1.4
Exception Type: MemcachedError
Exception Value:    
error 37 from memcached_set: SYSTEM ERROR(Resource temporarily unavailable), host: 127.0.0.1:11211 -> libmemcached/io.cc:358
Exception Location: /home/django/.virtualenvs/astrobiology-alpha/local/lib/python2.7/site-packages/django/core/cache/backends/memcached.py in set, line 64
Python Executable:  /home/django/.virtualenvs/astrobiology-alpha/bin/python
Python Version: 2.7.1
```

Most of my admin works, my guess is this article model is quite a big bigger than the others..

Please let me know how to debug this and if I can send you anything else that would be useful.

Thanks,
Shige

**Comment by jmoiron** [comment]
Shige, do you have a traceback?  

It's strange that memcached_set is reporting (Resource temporarily unavailable).  Memcached has a maximum data size of 1MB for any given key;  I thought it dealt with these types of failures in another way.

**Comment by typeshige** [comment]
Thanks for responding.

I hope this helps.

http://dpaste.com/775963/

**Comment by typeshige** [comment]
Looks like my dpaste went away.  Please let me know if you want another traceback.

Thanks,
Shige

**Comment by typeshige** [comment]
Just a quick update, I had to turn off johnny cache since its getting so many errors.

I still need to check all my libraries and perhaps get more memory.  My box has 16gb and it's using about 14 now.  I have my cache set to 512mb or so.  Is it too close using all my memory?

I think my machine can take 32 gb of ram so I'm going to try to buy some next week and would that have a chance of fixing things?  I figure I want probably a 2+ gb of cache once it works anyways.

Thanks.

**Comment by jmoiron** [comment]
Shige, I'm going to assume this was related to the issues you were having with memcached libs & connectivity in #4.  If not, please re-open this issue and paste the tb in a comment!
