### ISSUE TITLE
Globally enabling Johnny Cache in __init__.py causes error with syncdb

### ISSUE THREAD

**Issue by radiosilence** [jmoiron/johnny-cache#37]
`AttributeError: 'module' object has no attribute 'empty_iter'`

Solution:

```
import sys
try:
    if sys.argv[1] != 'syncdb':
        raise Exception
except:
    from johnny.cache import enable
    enable()
```

**Comment by jself** [comment]
Correct, this isn't possible. You can't enable jonny cache before the database and settings are initialized in the call order (this is why we do it in middleware, the call order is important)

**Comment by radiosilence** [comment]
Perhaps updating the docs then?

**Comment by jself** [comment]
Thanks, yeah, in fact it's documented as the opposite. I'll check on it to
make sure, I distinctly remember that not working though with similar
errors.
