### ISSUE TITLE
Is Johnny Cache compatible with PostgreSQL autocommit?

### ISSUE THREAD

**Issue by AudriusButkevicius** [jmoiron/johnny-cache#43]
The docs explain that this is a tricky part:
http://pythonhosted.org/johnny-cache/queryset_cache.html#transactions

But I am struggling to understand if autocommit causes any issues for Johnny?
Or does it make Johnny's life easier?

**Comment by AudriusButkevicius** [comment]
Also, just to make this clear, TransactionMiddleware is not used in my case.

**Comment by jself** [comment]
Autocommit, at least prior to 1.6, does not cause any issues with Johnny.
We're still working on 1.6 support unfortunately, but it'll be transparent
as well.

**Comment by AudriusButkevicius** [comment]
By saying prior 1.6 do you mean prior Johnny introduced support for Django 1.6, or Django versions prior 1.6?

In case it's the first case, what is the last commit usable by 1.5 with autocommit on?

**Comment by jself** [comment]
Django versions prior to 1.6, Johnny doesn't yet support Django 1.6

**Comment by AudriusButkevicius** [comment]
Thank you!
I suggest mentioning this in the docs.
