### ISSUE TITLE
Bump release?

### ISSUE THREAD

**Issue by Tatsh** [jmoiron/johnny-cache#62]
The latest version has a critical problem that stops it working from Django 1.6: `'Query' object has no attribute 'ordering_aliases'` which was fixed recently. I do not think we really want to have lines like `git+git://github.com/jmoiron/johnny-cache@7c8d3ab7aa2f2100c97b4c5bc5ef9120d2e72e9c#egg=johnny-cache` in requirements.txt and similar.

**Comment by jmoiron** [comment]
1.6a is now the default release on pypy (current master HEAD)
